"""Add directions and saved ingredients

Revision ID: ebf4581cf79b
Revises: 61a59d23dc72
Create Date: 2025-02-04 22:37:57.382920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf4581cf79b'
down_revision = '61a59d23dc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('common_unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_ingredients_id'), 'saved_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_saved_ingredients_name'), 'saved_ingredients', ['name'], unique=True)
    op.add_column('recipes', sa.Column('directions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'directions')
    op.drop_index(op.f('ix_saved_ingredients_name'), table_name='saved_ingredients')
    op.drop_index(op.f('ix_saved_ingredients_id'), table_name='saved_ingredients')
    op.drop_table('saved_ingredients')
    # ### end Alembic commands ###
